name: CI
on:
  push:
    branches: [master, release/**]
  pull_request:
    branches: [master, release/**]

jobs:
  # Build and Test the 'cucumber-tsflow' package
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone (required by Nerbank GitVersioning)
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install npm packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run specification tests
        run: npm test
