name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone (required by Nerbank GitVersioning)
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn build
      - run: yarn test:all
      - run: npm publish --provenance --access public ./cucumber-tsflow/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
