#
# This workflow creates a release from a specified branch. The Package version is managed
# by Nerdbank Gitversioning based on configuration held in 'version.json' file.
#
name: Release
on:
  workflow_dispatch:

jobs:
  # Build, Test and Pack the 'cucumber-tsflow' package
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone (required by Nerbank GitVersioning)
      - uses: actions/setup-dotnet@v1 # .NET Core is required in order to use nerdbank-gitversioning
        with:
          dotnet-version: 3.1.301
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install npm packages
        run: yarn
      - name: Update package version
        run: yarn set-packageversion
      - name: Build
        run: yarn build
      - name: Run specification tests
        run: yarn test

  # Publish the 'cucumber-tsflow' package to npm
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Publish npm package
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: $GITHUB_WORKSPACE/cucumber-tsflow/package.json
          access: public
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
